apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: cassandra-db
  name: cassandra-db
spec:
  ports:
    - name: "7000"
      port: 7000
      targetPort: 7000
    - name: "7001"
      port: 7001
      targetPort: 7001
    - name: "7199"
      port: 7199
      targetPort: 7199
    - name: "9042"
      port: 9042
      targetPort: 9042
    - name: "9160"
      port: 9160
      targetPort: 9160
  selector:
    io.kompose.service: cassandra-db
status:
  loadBalancer: {}